Removed silencer SBT plugin
The plugin is not necessary anymore since it was back-ported to all currently
supported compiler versions. It also breaks when using this library with the
3.3.1-RC1 Scala version:

```
[error] -- Error: typesafe/shared/src/main/scala/zio/config/typesafe/TypesafeConfigSource.scala:15:0
[error] undefined: new com.github.ghik.silencer.silent # -1: TermRef(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class ghik)),object silencer),silent),<init>) at readTasty
```

I also added a few improvements in the build itself, and fixed a few tests.